### ISSUE TITLE
Could not evaluate due to running error.

### ISSUE THREAD

**Issue by daanilogaspar** [yuqren/polarbplist#1]
Hi there,

Trying to evaluate your code I got the following message:

>> polar_platform
Undefined variable "nr5g" or class "nr5g.internal.polar.getN".

Error in nr_encode_part1 (line 16)
N = nr5g.internal.polar.getN(K, E, nMax);

Error in simulation_based_bp (line 11)
[N, froz_bits, info_bits, input_IL, sb_IL, IL, IB] = nr_encode_part1(TxRx.E, TxRx.K, TxRx.link_mode);

Error in polar_platform (line 44)
[fer, iter] = simulation_based_bp(TxRx);

Probably a missing file or toolbox?

Thx

**Comment by yuqren** [comment]
Hi, thanks for your interest. To run these codes, you should install 5G Toolbox in Matlab first. Please enter 'help nr5g.internal.polar.getN' in the command window for more information.
